### ISSUE TITLE
Getting an error: src is not a numpy array, neither a scalar

### ISSUE THREAD

**Issue by pawarpooja** [KiranPrakash/canny-edge-detection#1]
Hello sir, I want to apply thresholding on multiple images of a folder. I have tried the following code but its hitting an error as (TypeError: src is not a numpy array, neither a scalar). The code is :

import cv2
import matplotlib.pyplot as plt
from PIL import Image
import numpy as np
import os
from numpy import *

path1= 'D:\\Pooja\\dataset\\Base11'
path2='D:\\Pooja\\dataset\\new_img'
path3 = 'D:\\Pooja\\dataset\\thrshld_fldr'

img_rows=256
img_cols=256

listing = os.listdir(path1)
num_samples=size(listing)
print ('num_samples')

for file in listing:
    im = Image.open(path1 + '\\' + file)
    img = im.resize((img_rows, img_cols))
    gray = img.convert('L') 
    gray.save(path2 +'\\' + file,"JPEG")
    
    (thresh, im_bw) = cv2.threshold(np.asarray(gray), 128, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
    im_bw = cv2.threshold(gray, thresh, 255, cv2.THRESH_BINARY)[1]
    im_bw.save(path3 +'\\' + file,"JPEG")
*****************************************************************
This is the error page:

![error1](https://user-images.githubusercontent.com/29332279/34767075-403f6122-f61d-11e7-8a0c-4b0174d2b58d.jpg)

**Comment by KiranPrakash** [comment]
Please try using num.array or np.array in line 34 instead of np.asarray. If that doesn't work you could alternatively use cv2.imread() and cv2.cvtColor(). Note that, the program was written in python2.

**Comment by pawarpooja** [comment]
Thank you sir for resolving the issue!!

**Comment by KiranPrakash** [comment]
Glad that helped you to resolve! :)
